---
ansible_device_os: iosxr
cli:
  username: "{{ansible_user}}"
  password: "{{ansible_password}}"
  host: "{{inventory_hostname}}"
#  transport: cli
# Doesn't work in IOSXR module
# fatal: [xr1]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (iosxr_command) module: transport found in provider. Supported parameters include: host,password,port,ssh_keyfile,timeout,username"}
